lib/my_idea_web/router.ex
defmodule MyIdeaWeb.Router do
  use MyIdeaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MyIdeaWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/projects", ProjectController do
      resources "/suggestions", SuggestionController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MyIdeaWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MyIdeaWeb.Telemetry
    end
  end
end

lib/my_idea/web/project.ex
defmodule MyIdea.Web.Project do
  use Ecto.Schema
  import Ecto.Changeset

  schema "projects" do
    field :name, :string

    timestamps()
  end

  @doc false
  def changeset(project, attrs) do
    project
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end

lib/my_idea_web/controllers/project_controller.ex
defmodule MyIdeaWeb.ProjectController do
  use MyIdeaWeb, :controller

  alias MyIdea.Web
  alias MyIdea.Web.Project

  def index(conn, _params) do
    projects = Web.list_projects()
    render(conn, "index.html", projects: projects)
  end

  def new(conn, _params) do
    changeset = Web.change_project(%Project{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"project" => project_params}) do
    case Web.create_project(project_params) do
      {:ok, project} ->
        conn
        |> put_flash(:info, "Project created successfully.")
        |> redirect(to: Routes.project_path(conn, :show, project))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    project = Web.get_project!(id)
    suggestions = Web.list_suggestions_by_project!(id)
    render(conn, "show.html", project: project, suggestions: suggestions)
  end

  def edit(conn, %{"id" => id}) do
    project = Web.get_project!(id)
    changeset = Web.change_project(project)
    render(conn, "edit.html", project: project, changeset: changeset)
  end

  def update(conn, %{"id" => id, "project" => project_params}) do
    project = Web.get_project!(id)

    case Web.update_project(project, project_params) do
      {:ok, project} ->
        conn
        |> put_flash(:info, "Project updated successfully.")
        |> redirect(to: Routes.project_path(conn, :show, project))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", project: project, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    project = Web.get_project!(id)
    {:ok, _project} = Web.delete_project(project)

    conn
    |> put_flash(:info, "Project deleted successfully.")
    |> redirect(to: Routes.project_path(conn, :index))
  end
end

lib/my_idea_web/views/project_view.ex
defmodule MyIdeaWeb.ProjectView do
  use MyIdeaWeb, :view
end

lib/my_idea_web/templates/project/edit.html.eex
<h1>Edit Project</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.project_path(@conn, :update, @project)) %>

<span><%= link "Back", to: Routes.project_path(@conn, :index) %></span>

lib/my_idea_web/templates/project/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/my_idea_web/templates/project/index.html.eex
<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for project <- @projects do %>
    <tr>
      <td><%= project.name %></td>

      <td>
        <span><%= link "Show", to: Routes.project_path(@conn, :show, project) %></span>
        <span><%= link "Edit", to: Routes.project_path(@conn, :edit, project) %></span>
        <span><%= link "Delete", to: Routes.project_path(@conn, :delete, project), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Project", to: Routes.project_path(@conn, :new) %></span>

lib/my_idea_web/templates/project/new.html.eex
<h1>New Project</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.project_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.project_path(@conn, :index) %></span>

lib/my_idea_web/templates/project/show.html.eex
<h1>Show Project</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @project.name %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.project_path(@conn, :edit, @project) %></span>
<span><%= link "Back", to: Routes.project_path(@conn, :index) %></span>


<h1>Listing Suggestions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for suggestion <- @suggestions do %>
    <tr>
      <td><%= suggestion.title %></td>
      <td><%= suggestion.description %></td>

      <td>
        <span><%= link "Show", to: Routes.project_suggestion_path(@conn, :show, @project.id, suggestion) %></span>
        <span><%= link "Edit", to: Routes.project_suggestion_path(@conn, :edit, @project.id, suggestion) %></span>
        <span><%= link "Delete", to: Routes.project_suggestion_path(@conn, :delete, @project.id, suggestion), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Suggestion", to: Routes.project_suggestion_path(@conn, :new, @project.id) %></span>