lib/my_idea_web/router.ex
defmodule MyIdeaWeb.Router do
  use MyIdeaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MyIdeaWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/projects", ProjectController do
      resources "/suggestions", SuggestionController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MyIdeaWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MyIdeaWeb.Telemetry
    end
  end
end

lib/my_idea_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "My Idea" %></h1>
</section>

<section class="row">
  <article class="column">
    <h2>Projects</h2>
    <ul>
      <li><%= link "projects", to: Routes.project_path(@conn, :index) %></li>
    </ul>
  </article>
</section>